apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gif-app.fullname" . }}
  labels:
    {{- include "gif-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gif-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gif-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: gif-app
          image: mcaci/gif-app
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP