apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: gif-app-addrpool
  namespace: default
spec:
  addresses:
  - 172.18.255.200-172.18.255.250
# spec:
#   addresses:
#   - 192.168.10.0/24
#   - 192.168.9.1-192.168.9.5
#   - fc00:f853:0ccd:e799::/124
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: gif-app-l2adv
  namespace: default
