apiVersion: v1
kind: Service
metadata:
  name: {{ include "gif-app.fullname" . }}
  labels:
    {{- include "gif-app.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "gif-app.selectorLabels" . | nindent 4 }}