apiVersion: v2
name: gif-app
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.0.1"

keywords:
  - gif

sources:
  - https://github.com/mcaci/gif-app

maintainers:
  - name: Michele Caci
    URL: https://github.com/mcaci/mcaci

# dependencies:
# # cannot have two deps with same name and diff version
  # run helm dependency upgrade *helm dep up*
# - name: metallb
#   version: ^v0
#   repository: "https://metallb.github.io/metallb"